VOLUME_BASE_PATH = "./nlp-mentalhealth-data"
VOLUME_DATASETS_BASE_PATH = f"{VOLUME_BASE_PATH}/datasets"
VOLUME_MODEL_CHECKPOINTS_BASE_PATH = f"{VOLUME_BASE_PATH}/checkpoints"
VOLUME_SAVED_MODELS_BASE_PATH = f"{VOLUME_BASE_PATH}/saved_models"
VOLUME_CACHE_DIR = f"{VOLUME_BASE_PATH}/cache"
VOLUME_METRICS_DIR = f"{VOLUME_BASE_PATH}/metrics"

HUGGINGFACE_ACCESS_TOKEN = ""